---
- name: Restart timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
