#!/usr/bin/env bash
# backup-suricata-s.sh — Run on .20 (ssh s) to collect all config + state
# Usage: bash backup-suricata-s.sh [--no-snort] [--no-binaries]
# Output: /root/soc-s-backup-$(date).tar.gz  (then scp it off)
#
# Snort 3 is included by default. Pass --no-snort to skip it.
# Binaries (snort, loki, promtail, velociraptor) included by default. Pass --no-binaries to skip.
#
# Always excluded (regenerable on restore):
#   - misp.rules, suricata.rules  — rebuilt by suricata-update + MISP pull
#   - GeoIP mmdb files            — re-downloaded by geoipupdate
#   - /var/lib/suricata/rules/suricata.rules  (merged ruleset, ~60MB)

set -euo pipefail

INCLUDE_SNORT=true
INCLUDE_BINARIES=true
for arg in "$@"; do
    [ "$arg" = "--no-snort" ]    && INCLUDE_SNORT=false
    [ "$arg" = "--no-binaries" ] && INCLUDE_BINARIES=false
done

STAMP=$(date +%Y%m%d-%H%M%S)
WORKDIR="/tmp/soc-s-backup-${STAMP}"
OUT="/root/soc-s-backup-${STAMP}.tar.gz"

# Clean up staging dir on exit or interrupt
trap 'rm -rf "${WORKDIR}"' EXIT

echo "[+] Backup started — staging in ${WORKDIR}"
mkdir -p "${WORKDIR}"

cp_if() {
    local src="$1"
    local dst="${WORKDIR}${src}"
    if [ -e "$src" ]; then
        mkdir -p "$(dirname "$dst")"
        cp -a "$src" "$dst" 2>/dev/null && echo "    OK  $src" || echo "    ERR $src"
    else
        echo "    --  $src (missing)"
    fi
}

cp_dir() {
    local src="$1"
    local dst="${WORKDIR}${src}"
    if [ -d "$src" ]; then
        mkdir -p "$(dirname "$dst")"
        cp -a "$src" "$dst" 2>/dev/null && echo "    OK  $src/" || echo "    ERR $src/"
    else
        echo "    --  $src/ (missing)"
    fi
}

# ─── Suricata ──────────────────────────────────────────────────────────────
echo "[+] Suricata core config"
cp_if /etc/suricata/suricata.yaml
# Copy /etc/suricata/rules but exclude misp.rules (~156MB, regenerated by misp-pull-rules.sh on restore)
if [ -d /etc/suricata/rules ]; then
    mkdir -p "${WORKDIR}/etc/suricata/rules"
    cp -a /etc/suricata/rules/. "${WORKDIR}/etc/suricata/rules/" 2>/dev/null || true
    rm -f "${WORKDIR}/etc/suricata/rules/misp.rules" 2>/dev/null || true
    echo "    OK  /etc/suricata/rules/ (misp.rules excluded — regenerable)"
else
    echo "    --  /etc/suricata/rules/ (missing)"
fi
cp_dir /etc/suricata/iprep
cp_if /etc/suricata/threshold.config
cp_if /etc/suricata/disable.conf
cp_if /etc/suricata/enable.conf
cp_if /etc/suricata/modify.conf
cp_if /var/lib/suricata/rules/local.rules
# suricata.rules (merged ruleset ~60MB) intentionally excluded — regenerated by suricata-update on restore
cp_if /var/lib/suricata/update.yaml             # suricata-update state
cp_if /etc/suricata/update.yaml                 # suricata-update sources config
cp_dir /etc/suricata/update

echo "[+] Suricata-update sources"
suricata-update list-sources --enabled 2>/dev/null > "${WORKDIR}/suricata-update-enabled-sources.txt" || true

# ─── Custom scripts ────────────────────────────────────────────────────────
echo "[+] Custom /usr/local/bin scripts"
cp_if /usr/local/bin/suricata-iprep-update.sh
cp_if /usr/local/bin/misp-pull-rules.sh
cp_if /usr/local/bin/misp-push-sightings.py
cp_if /usr/local/bin/suricata-enforcer.py

# ─── Cron ──────────────────────────────────────────────────────────────────
echo "[+] Crontabs"
cp_if /var/spool/cron/crontabs/root
cp_dir /etc/cron.d

# ─── fail2ban ──────────────────────────────────────────────────────────────
echo "[+] fail2ban"
cp_if /etc/fail2ban/jail.local
cp_dir /etc/fail2ban/jail.d
cp_dir /etc/fail2ban/filter.d
cp_dir /etc/fail2ban/action.d

# ─── Promtail ──────────────────────────────────────────────────────────────
echo "[+] Promtail"
cp_dir /etc/promtail
if [ "${INCLUDE_BINARIES}" = "true" ]; then cp_if /usr/local/bin/promtail; else echo "    --  /usr/local/bin/promtail (--no-binaries)"; fi

# ─── Loki ──────────────────────────────────────────────────────────────────
echo "[+] Loki"
cp_dir /etc/loki
if [ "${INCLUDE_BINARIES}" = "true" ]; then cp_if /usr/local/bin/loki; else echo "    --  /usr/local/bin/loki (--no-binaries)"; fi

# ─── Grafana ───────────────────────────────────────────────────────────────
echo "[+] Grafana"
cp_if /etc/grafana/grafana.ini
cp_dir /etc/grafana/provisioning
# Dashboard JSON files (provisioned or manually saved)
if [ -d /var/lib/grafana/dashboards ]; then
    find /var/lib/grafana/dashboards -name "*.json" | while read -r f; do
        cp_if "$f"
    done
fi
# Grafana sqlite DB (contains datasources/dashboards if not file-provisioned)
cp_if /var/lib/grafana/grafana.db

# ─── EveBox ────────────────────────────────────────────────────────────────
echo "[+] EveBox"
cp_dir /etc/evebox
if [ "${INCLUDE_BINARIES}" = "true" ]; then cp_if /usr/local/bin/evebox; else echo "    --  /usr/local/bin/evebox (--no-binaries)"; fi

# ─── Velociraptor ──────────────────────────────────────────────────────────
echo "[+] Velociraptor"
cp_dir /etc/velociraptor
if [ "${INCLUDE_BINARIES}" = "true" ]; then cp_if /usr/local/bin/velociraptor; else echo "    --  /usr/local/bin/velociraptor (--no-binaries)"; fi

# ─── Arkime ────────────────────────────────────────────────────────────────
echo "[+] Arkime"
cp_dir /opt/arkime/etc
cp_if /etc/arkime/config.ini

# ─── Filebeat ──────────────────────────────────────────────────────────────
echo "[+] Filebeat"
cp_dir /etc/filebeat

# ─── Wazuh agent ───────────────────────────────────────────────────────────
echo "[+] Wazuh agent"
cp_dir /var/ossec/etc

# ─── GeoIP ─────────────────────────────────────────────────────────────────
echo "[+] GeoIP"
cp_if /etc/GeoIP.conf          # credentials + config — always back up
# mmdb files intentionally excluded — re-downloaded by geoipupdate on restore (~85MB total)

# ─── Logrotate ─────────────────────────────────────────────────────────────
echo "[+] Logrotate"
cp_if /etc/logrotate.d/suricata
cp_if /etc/logrotate.d/grafana
cp_if /etc/logrotate.d/loki
cp_if /etc/logrotate.d/promtail

# ─── Systemd units (custom only) ───────────────────────────────────────────
echo "[+] Systemd units"
cp_dir /etc/systemd/system
systemctl list-unit-files --state=enabled --no-legend 2>/dev/null > "${WORKDIR}/systemd-enabled-units.txt" || true

# ─── Network interface config ──────────────────────────────────────────────
echo "[+] Network / interface"
cp_if /etc/network/interfaces
cp_dir /etc/network/interfaces.d   # includes enp0s8-promisc
cp_dir /etc/netplan                # fixed: was cp_if (netplan is a directory)
ip link show 2>/dev/null > "${WORKDIR}/ip-link-show.txt" || true

# ─── APT package list ──────────────────────────────────────────────────────
echo "[+] Package list"
dpkg --get-selections > "${WORKDIR}/dpkg-selections.txt" 2>/dev/null || true
dpkg -l | grep -E "suricata|snort|grafana|loki|promtail|filebeat|wazuh|evebox|geoip|fail2ban|arkime|veloci" \
    > "${WORKDIR}/key-packages.txt" 2>/dev/null || true
apt-mark showmanual > "${WORKDIR}/apt-manual.txt" 2>/dev/null || true

# ─── APT repo sources ──────────────────────────────────────────────────────
echo "[+] APT sources"
cp_dir /etc/apt/sources.list.d
cp_if /etc/apt/sources.list
cp_dir /etc/apt/trusted.gpg.d
cp_dir /etc/apt/keyrings

# ─── MISP integration state ────────────────────────────────────────────────
echo "[+] MISP state"
cp_if /var/lib/suricata/misp-sighting-offset

# ─── Snort 3 (optional) ────────────────────────────────────────────────────
if [ "${INCLUDE_SNORT}" = "true" ]; then
    echo "[+] Snort 3 config + rules"
    # Copy /etc/snort but exclude misp.rules (~83MB, regenerable via snort3-update-rules.sh)
    if [ -d /etc/snort ]; then
        mkdir -p "${WORKDIR}/etc/snort"
        cp -a /etc/snort/. "${WORKDIR}/etc/snort/" 2>/dev/null || true
        rm -f "${WORKDIR}/etc/snort/rules/misp.rules" 2>/dev/null || true
        echo "    OK  /etc/snort/ (misp.rules excluded — regenerable)"
    else
        echo "    --  /etc/snort/ (missing)"
    fi
    cp_if /usr/local/bin/snort3-update-rules.sh
    cp_if /etc/logrotate.d/snort3
    cp_if /etc/systemd/system/snort3.service

    if [ "${INCLUDE_BINARIES}" = "true" ]; then
        echo "[+] Snort 3 installed binaries + DAQ libs"
        cp_if /usr/local/bin/snort
        cp_dir /usr/local/lib/daq                      # af_packet_daq.so etc.
        find /usr/local/lib -maxdepth 1 -name "libdaq*" 2>/dev/null | while read -r f; do
            cp_if "$f"
        done
        cp_dir /usr/local/lib/snort_extra 2>/dev/null || true
    else
        echo "    --  Snort binaries + DAQ libs (--no-binaries)"
    fi

    # Record exact version + build info for reference (always)
    /usr/local/bin/snort --version 2>&1 | head -5 > "${WORKDIR}/snort-version.txt" || true
    echo "    Snort version recorded → snort-version.txt"

    # Record source tarball locations (not copied — too large)
    echo "[+] Snort 3 source tarball paths (not copied)"
    {
        find /usr/local/src /root -maxdepth 1 \
            \( -name "snort3-*.tar.gz" -o -name "libdaq-*.tar.gz" \) \
            2>/dev/null || true
        echo "(search complete)"
    } > "${WORKDIR}/snort-source-tarballs.txt"
else
    echo "[+] Snort 3 — skipped (--no-snort)"
fi

# ─── Pack it up ────────────────────────────────────────────────────────────
echo "[+] Creating tarball → ${OUT}"
# Disable EXIT trap so we can remove WORKDIR manually after tar
trap - EXIT
tar -czf "${OUT}" -C /tmp "soc-s-backup-${STAMP}"
rm -rf "${WORKDIR}"

SIZE=$(du -h "${OUT}" | cut -f1)
echo "[+] Done. Archive: ${OUT} (${SIZE})"
echo ""
echo "    Fetch with:"
echo "      scp root@192.168.1.20:${OUT} ."
